### ISSUE TITLE
negative number literal in built-in `numEncoding` throws wrongly

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/lambda-calculus#100]
When using a built-in `numEncoding`, negative number literals ( in this case, _minus_ one ) throw with

```
toInt: \ s z . s z is not a number in numEncoding Church

TypeError: term is not a function
    at toInt (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:140:22)
```

Note that it's `toInt` that throws, not `fromInt`. I'm not sure what happens here.

**Comment by JohanWiltink** [comment]
Cannot reproduce the problem with current compiler in test environment. Possibly it's an interaction between CW environment and `Error`s from compiler; possibly it's just an incomplete compiler version on CW.

Test environment correctly throws with

```javascript
fromInt.Church: negative number -1

RangeError
    at fromInt (file:///C:/Users/Johan/src/codewars-lambda-calculus/src/lambda-calculus.js:110:13)
```

Defer until newer version ( `v1.0.5+` ) with full support for negative numbers can be tested on CW.

**Comment by JohanWiltink** [comment]
Problem not reproducible in `v1.1`
