### ISSUE TITLE
define Y as JS?

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/lambda-calculus#102]
`Y` definition ( line 102 ) is in LC and has to be evaluated on every use ( line 199 ). It _may_ be faster to define it as a JS function:
```javascript
Z = f => x => f (Z(f)) (x) ;
```
This has to be tested to actually be a performance improvement before being changed though.

**Comment by JohanWiltink** [comment]
change craps out in tests/scott-lists/solution.txt/last#245:

```
eval: evaluating undefined inside definition of last

EvalError
    at runEval (file:///C:/Users/Johan/src/codewars-lambda-calculus/src/lambda-calculus.js:372:83)
    at evalLC (file:///C:/Users/Johan/src/codewars-lambda-calculus/src/lambda-calculus.js:427:10)
    at Object.get [as last] (file:///C:/Users/Johan/src/codewars-lambda-calculus/src/lambda-calculus.js:341:54)
    at file:///C:/Users/Johan/src/codewars-lambda-calculus/tests/scott-lists/test.js:25:13
```

well, that's why we have testing I suppose.

**Comment by JohanWiltink** [comment]
change that `()` to `undefined = \ _ . ()`, and it compiles.

then all Hell breaks loose. I guess JS `Z` is not a good idea.

**Comment by JohanWiltink** [comment]
It forces strictness on way too many things. No, not a good idea.
