### ISSUE TITLE
Reading properties of JS values fails if value is undefined

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/lambda-calculus#87]
```
TypeError: Cannot read properties of null (reading 'term')
    at runEval (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:395:20)
    at result (file:///workspace/node_modules/@codewars/lambda-calculus/src/lambda-calculus.js:336:16)
```

This error was encountered in this code in line 395 of `runeval`

```
        } else { // lastTerm is a JS function
          const res = lastTerm(term);
          if ( res.term ) {
            ({term, env} = res);
            if ( ! env ) env = new Env;
          } else
            term = res;
        }
```

`res` may be `null` or `undefined`, and `res.term` should be `res?.term`

**Comment by JohanWiltink** [comment]
See also Submit testing [here](https://www.codewars.com/kumite/62579186a071210017c8346d) - that triggered the error
